site_name: CiviVolunteer
repo_url: https://github.com/civicrm/org.civicrm.volunteer
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.magiclink
pages:
- Introduction: index.md
- Installation: installation.md
- Configuration: configuration.md
- Volunteer Interest Form: interests.md
- Search for Volunteer Opportunities: opportunities.md
- New Volunteer Project: projects.md
- Events: events.md
- Reports: reports.md
- Examples: examples.md