site_name: CiviVolunteer
repo_url: https://github.com/civicrm/org.civicrm.volunteer
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.magiclink
pages:
- Introduction: index.md
- Installation: installation.md
- Configuration: configuration.md
- Volunteer Interest Form: interests.md
- Search for Volunteer Opportunities: opportunities.md
- New Volunteer Project: projects.md
- Events: events.md
- Reports: reports.md
- Examples & Other Resources: resources.md
- Release notes:
  - 1.4 release: release/1.4.md
  - 2.0 release: release/2.0.md
  - 2.2 release: release/2.2.md
- Developer docs:
  - hook_civicrm_volunteer_projectDefaultSettings: dev/hooks/hook_civicrm_volunteer_projectDefaultSettings.md